// Package featuretypes holds Appendix D of the Census Bureau's TIGER/Line
// technical documentation as data.
//
// A TIGER FEATNAMES record does not carry a street name as a string. It
// carries a base name and four codes around it — PREQUAL, PRETYP, SUFTYP,
// SUFQUAL — and the name a reader recognizes only exists once those codes are
// expanded. This table is the SUFTYP and PRETYP half: the 503 feature types
// the Census Bureau names, with the abbreviation it displays for each.
//
// It is not Publication 28 Appendix C1 and must not be substituted for it.
// The two overlap on the ordinary street suffixes and disagree on the
// abbreviation for several of them, and this one carries hundreds of rows
// Publication 28 has no equivalent for — ACUEDUCTO, AIR FORCE BASE, ZOO. A
// consumer producing Project US@ output reads the Census abbreviation here and
// then resolves the word through streetsuffixes; reading only one of the two
// is what produces a key that misses.
//
// Rows are uppercase, following the rest of this module. The published table
// prints them in title case.
//
// Transcribed from
// https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2025/TGRSHP2025_TechDoc_D.pdf
// (TIGER/Line Shapefiles, 2025, Appendix D: Feature Name Types).
package featuretypes

import (
	"iter"
	"slices"
)

// FeatureType is one row of Appendix D.
//
// Code is the value TIGER writes into PRETYP and SUFTYP; it is the only field
// a reader of those fields has to start from. Prefix and Suffix report which
// of the two the Census Bureau permits the type in, and both are false for no
// row in the published table — every type is allowed somewhere.
//
// Translation is set only on the Spanish rows, and it is prose rather than a
// pointer: the Census Bureau's own English rendering of the word. Most of them
// name another row here (ACUEDUCTO translates AQUEDUCT, which is code 118),
// but some do not — AUTOPISTA translates "EXPRESSWAY OR FREEWAY" — so a
// consumer must not look a Translation up in this table and expect to find it.
type FeatureType struct {
	Code        string
	Full        string
	Short       string
	Spanish     bool
	Translation string
	Prefix      bool
	Suffix      bool
}

var featureTypes = []FeatureType{
	{Code: "103", Full: "ACADEMY", Short: "ACDMY", Prefix: true, Suffix: true},
	{Code: "104", Full: "ACUEDUCTO", Short: "ACUEDUCTO", Spanish: true, Translation: "AQUEDUCT", Prefix: true},
	{Code: "105", Full: "AEROPUERTO", Short: "AERO", Spanish: true, Translation: "AIRPORT", Prefix: true},
	{Code: "106", Full: "AIR FORCE BASE", Short: "AFB", Suffix: true},
	{Code: "107", Full: "AIRFIELD", Short: "AIRFIELD", Suffix: true},
	{Code: "108", Full: "AIRPARK", Short: "AIRPARK", Suffix: true},
	{Code: "109", Full: "AIRPORT", Short: "ARPRT", Suffix: true},
	{Code: "110", Full: "AIRSTRIP", Short: "AIRSTRIP", Suffix: true},
	{Code: "112", Full: "ALLEY", Short: "ALY", Suffix: true},
	{Code: "115", Full: "APARTMENT BUILDING", Short: "APT BLDG", Suffix: true},
	{Code: "116", Full: "APARTMENT COMPLEX", Short: "APT COMPLEX", Suffix: true},
	{Code: "117", Full: "APARTMENTS", Short: "APTS", Suffix: true},
	{Code: "118", Full: "AQUEDUCT", Short: "AQUEDUCT", Suffix: true},
	{Code: "119", Full: "ARCADE", Short: "ARC", Prefix: true, Suffix: true},
	{Code: "121", Full: "ARROYO", Short: "ARROYO", Spanish: true, Translation: "STREAM ", Prefix: true},
	{Code: "122", Full: "ASSISTED LIVING CENTER", Short: "ASSTD LIV CTR", Suffix: true},
	{Code: "694", Full: "ASSISTED LIVING FACILITY", Short: "ASSTD LIV FAC", Suffix: true},
	{Code: "123", Full: "AUTOPISTA", Short: "AUTOPISTA", Spanish: true, Translation: "EXPRESSWAY OR FREEWAY ", Prefix: true},
	{Code: "124", Full: "AVENIDA", Short: "AVE", Spanish: true, Translation: "AVENUE ", Prefix: true},
	{Code: "125", Full: "AVENUE", Short: "AVE", Prefix: true, Suffix: true},
	{Code: "126", Full: "BAHIA", Short: "BAHÍA", Spanish: true, Translation: "BAY ", Prefix: true},
	{Code: "127", Full: "BANK", Short: "BK", Prefix: true, Suffix: true},
	{Code: "704", Full: "BASE", Short: "BASE", Suffix: true},
	{Code: "128", Full: "BASIN", Short: "BASIN", Suffix: true},
	{Code: "129", Full: "BAY", Short: "BAY", Prefix: true, Suffix: true},
	{Code: "130", Full: "BAYOU", Short: "BYU", Prefix: true, Suffix: true},
	{Code: "131", Full: "BEACH", Short: "BCH", Suffix: true},
	{Code: "132", Full: "BED AND BREAKFAST", Short: "B AND B", Suffix: true},
	{Code: "136", Full: "BELTWAY", Short: "BELTWAY", Suffix: true},
	{Code: "137", Full: "BEND", Short: "BND", Suffix: true},
	{Code: "138", Full: "BLUFF", Short: "BLF", Suffix: true},
	{Code: "139", Full: "BOARDING HOUSE", Short: "BRDNG HSE", Suffix: true},
	{Code: "140", Full: "BOG", Short: "BOG", Suffix: true},
	{Code: "141", Full: "BOSQUE", Short: "BOSQUE", Spanish: true, Translation: "FOREST ", Prefix: true},
	{Code: "142", Full: "BOULEVARD", Short: "BLVD", Prefix: true, Suffix: true},
	{Code: "143", Full: "BOUNDARY", Short: "BOUNDARY", Suffix: true},
	{Code: "146", Full: "BRANCH", Short: "BR", Prefix: true, Suffix: true},
	{Code: "147", Full: "BRIDGE", Short: "BRG", Suffix: true},
	{Code: "148", Full: "BROOK", Short: "BRK", Suffix: true},
	{Code: "149", Full: "BUILDING", Short: "BLDG", Prefix: true, Suffix: true},
	{Code: "150", Full: "BULEVAR", Short: "BULEVAR", Spanish: true, Translation: "BOULEVARD ", Prefix: true},
	{Code: "151", Full: "BUREAU OF INDIAN AFFAIRS HIGHWAY", Short: "BIA HWY", Prefix: true},
	{Code: "152", Full: "BUREAU OF INDIAN AFFAIRS ROAD", Short: "BIA RD", Prefix: true},
	{Code: "153", Full: "BUREAU OF INDIAN AFFAIRS ROUTE", Short: "BIA RTE", Prefix: true},
	{Code: "154", Full: "BUREAU OF LAND MANAGEMENT ROAD", Short: "BLM RD", Prefix: true},
	{Code: "696", Full: "BYPASS", Short: "BYP", Prefix: true, Suffix: true},
	{Code: "156", Full: "CALLE", Short: "CLL", Spanish: true, Translation: "STREET ", Prefix: true},
	{Code: "157", Full: "CALLEJA", Short: "CALLEJA", Spanish: true, Translation: "NARROW STREET ", Prefix: true},
	{Code: "158", Full: "CALLEJÓN", Short: "CALLEJÓN", Spanish: true, Translation: "ALLEY ", Prefix: true},
	{Code: "159", Full: "CAMINITO", Short: "CMT", Spanish: true, Translation: "LITTLE ROAD ", Prefix: true},
	{Code: "160", Full: "CAMINO", Short: "CAM", Spanish: true, Translation: "ROAD OR WAY ", Prefix: true},
	{Code: "161", Full: "CAMP", Short: "CP", Prefix: true, Suffix: true},
	{Code: "163", Full: "CAMPGROUND", Short: "CMPGRND", Suffix: true},
	{Code: "164", Full: "CAMPUS", Short: "CMPS", Suffix: true},
	{Code: "165", Full: "CANAL", Short: "CNL", Prefix: true, Suffix: true},
	{Code: "172", Full: "CANO", Short: "CAÑO", Spanish: true, Translation: "DRAIN OR SEWER ", Prefix: true},
	{Code: "166", Full: "CANTERA", Short: "CANTERA", Spanish: true, Translation: "QUARRY OR GRAVEL PIT", Prefix: true},
	{Code: "167", Full: "CANYON", Short: "CYN", Prefix: true, Suffix: true},
	{Code: "168", Full: "CAPILLA", Short: "CAPILLA", Spanish: true, Translation: "CHAPEL ", Prefix: true},
	{Code: "169", Full: "CARRETERA", Short: "CARR", Spanish: true, Translation: "ROAD ", Prefix: true},
	{Code: "170", Full: "CAUSEWAY", Short: "CSWY", Suffix: true},
	{Code: "171", Full: "CAYO", Short: "CAYO", Spanish: true, Translation: "KEY ", Prefix: true},
	{Code: "173", Full: "CEMENTERIO", Short: "CEM", Spanish: true, Translation: "CEMETERY ", Prefix: true},
	{Code: "174", Full: "CEMETERY", Short: "CMTRY", Suffix: true},
	{Code: "175", Full: "CENTER", Short: "CTR", Prefix: true, Suffix: true},
	{Code: "176", Full: "CENTRO", Short: "CENTRO", Spanish: true, Translation: "CENTER ", Prefix: true},
	{Code: "177", Full: "CERRADA", Short: "CER", Spanish: true, Translation: "CLOSED ", Prefix: true},
	{Code: "178", Full: "CHAMBER OF COMMERCE", Short: "CHAM OF COM", Suffix: true},
	{Code: "179", Full: "CHANNEL", Short: "CHNNL", Suffix: true},
	{Code: "180", Full: "CHAPEL", Short: "CPL", Prefix: true, Suffix: true},
	{Code: "181", Full: "CHILDRENS HOME", Short: "CHILDRENS HOME", Suffix: true},
	{Code: "182", Full: "CHURCH", Short: "CHURCH", Prefix: true, Suffix: true},
	{Code: "183", Full: "CIRCLE", Short: "CIR", Suffix: true},
	{Code: "234", Full: "CÍRCULO", Short: "CÍR", Spanish: true, Translation: "CIRCLE ", Prefix: true},
	{Code: "184", Full: "CITY HALL", Short: "CITY HALL", Suffix: true},
	{Code: "185", Full: "CITY PARK", Short: "CITY PARK", Suffix: true},
	{Code: "186", Full: "CLIFF", Short: "CLF", Suffix: true},
	{Code: "187", Full: "CLUB", Short: "CLB", Prefix: true, Suffix: true},
	{Code: "188", Full: "COLEGIO", Short: "COLEGIO", Spanish: true, Translation: "SCHOOL ", Prefix: true},
	{Code: "189", Full: "COLLEGE", Short: "COLG", Prefix: true, Suffix: true},
	{Code: "190", Full: "COMMON", Short: "CMN", Suffix: true},
	{Code: "191", Full: "COMMONS", Short: "CMNS", Prefix: true, Suffix: true},
	{Code: "192", Full: "COMMUNITY CENTER", Short: "COMMUNITY CTR", Suffix: true},
	{Code: "193", Full: "COMMUNITY COLLEGE", Short: "COMMUNITY COLG", Prefix: true, Suffix: true},
	{Code: "194", Full: "COMMUNITY PARK", Short: "COMMUNITY PARK", Prefix: true, Suffix: true},
	{Code: "195", Full: "COMPLEX", Short: "COMPLX", Suffix: true},
	{Code: "197", Full: "CONDOMINIOS", Short: "CONDIOS", Spanish: true, Translation: "CONDOMINIUMS ", Prefix: true},
	{Code: "198", Full: "CONDOMINIUM", Short: "CONDO", Prefix: true, Suffix: true},
	{Code: "199", Full: "CONDOMINIUMS", Short: "CONDOS", Suffix: true},
	{Code: "201", Full: "CONVENT", Short: "CNVNT", Prefix: true, Suffix: true},
	{Code: "202", Full: "CONVENTION CENTER", Short: "CONVENTION CTR", Prefix: true, Suffix: true},
	{Code: "203", Full: "CORNERS", Short: "CORS", Suffix: true},
	{Code: "204", Full: "CORRECTIONAL FACILITY", Short: "CORR FACLTY", Suffix: true},
	{Code: "205", Full: "CORRECTIONAL INSTITUTE", Short: "CORR INST", Suffix: true},
	{Code: "207", Full: "CORTE", Short: "CORTE", Spanish: true, Translation: "COURT ", Prefix: true},
	{Code: "679", Full: "COTTAGE", Short: "COTTAGE", Suffix: true},
	{Code: "208", Full: "COULEE", Short: "COULEE", Suffix: true},
	{Code: "209", Full: "COUNTRY CLUB", Short: "COUNTRY CLUB", Prefix: true, Suffix: true},
	{Code: "210", Full: "COUNTY HIGHWAY", Short: "CO HWY", Prefix: true},
	{Code: "211", Full: "COUNTY HOME", Short: "CO HOME", Prefix: true, Suffix: true},
	{Code: "212", Full: "COUNTY LANE", Short: "CO LN", Prefix: true},
	{Code: "213", Full: "COUNTY PARK", Short: "CO PARK", Suffix: true},
	{Code: "214", Full: "COUNTY ROAD", Short: "CO RD", Prefix: true},
	{Code: "215", Full: "COUNTY ROUTE", Short: "CO RTE", Prefix: true},
	{Code: "216", Full: "COUNTY STATE AID HIGHWAY", Short: "CO ST AID HWY", Prefix: true},
	{Code: "217", Full: "COUNTY TRUNK HIGHWAY", Short: "CO TRUNK HWY", Prefix: true},
	{Code: "218", Full: "COUNTY TRUNK ROAD", Short: "CO TRUNK RD", Prefix: true},
	{Code: "219", Full: "COURSE", Short: "CRS", Suffix: true},
	{Code: "220", Full: "COURT", Short: "CT", Prefix: true, Suffix: true},
	{Code: "221", Full: "COURTHOUSE", Short: "COURTHOUSE", Suffix: true},
	{Code: "222", Full: "COURTS", Short: "CTS", Suffix: true},
	{Code: "223", Full: "COVE", Short: "CV", Suffix: true},
	{Code: "225", Full: "CREEK", Short: "CRK", Suffix: true},
	{Code: "226", Full: "CRESCENT", Short: "CRES", Suffix: true},
	{Code: "227", Full: "CREST", Short: "CRST", Suffix: true},
	{Code: "228", Full: "CROSSING", Short: "XING", Suffix: true},
	{Code: "229", Full: "CROSSROADS", Short: "XROAD", Prefix: true, Suffix: true},
	{Code: "233", Full: "CUTOFF", Short: "CUTOFF", Suffix: true},
	{Code: "235", Full: "DAM", Short: "DM", Suffix: true},
	{Code: "236", Full: "DELTA ROAD", Short: "DELTA RD", Prefix: true},
	{Code: "237", Full: "DEPARTMENT", Short: "DEPT", Prefix: true, Suffix: true},
	{Code: "238", Full: "DEPOT", Short: "DEP", Suffix: true},
	{Code: "239", Full: "DETENTION CENTER", Short: "DETENTION CTR", Suffix: true},
	{Code: "240", Full: "DISTRICT OF COLUMBIA HIGHWAY", Short: "DC HWY", Prefix: true},
	{Code: "241", Full: "DITCH", Short: "DITCH", Prefix: true, Suffix: true},
	{Code: "242", Full: "DIVIDE", Short: "DV", Suffix: true},
	{Code: "243", Full: "DOCK", Short: "DOCK", Suffix: true},
	{Code: "244", Full: "DORMITORY", Short: "DORMITORY", Suffix: true},
	{Code: "245", Full: "DRAIN", Short: "DRN", Suffix: true},
	{Code: "246", Full: "DRAW", Short: "DRAW", Suffix: true},
	{Code: "247", Full: "DRIVE", Short: "DR", Suffix: true},
	{Code: "248", Full: "DRIVEWAY", Short: "DRIVEWAY", Prefix: true, Suffix: true},
	{Code: "249", Full: "DUMP", Short: "DUMP", Suffix: true},
	{Code: "251", Full: "EDIFICIO", Short: "EDIF", Spanish: true, Translation: "BUILDING ", Prefix: true},
	{Code: "252", Full: "ELEMENTARY SCHOOL", Short: "ELEM SCHOOL", Suffix: true},
	{Code: "253", Full: "ENSENADA", Short: "ENSENADA", Spanish: true, Translation: "COVE ", Prefix: true},
	{Code: "254", Full: "ENTRADA", Short: "ENT", Spanish: true, Translation: "ENTRANCE ", Prefix: true},
	{Code: "256", Full: "ESCUELA", Short: "ESCUELA", Spanish: true, Translation: "SCHOOL ", Prefix: true},
	{Code: "680", Full: "ESPLANADE", Short: "ESPLANADE", Spanish: true, Translation: "ESPLANADE", Prefix: true, Suffix: true},
	{Code: "257", Full: "ESTATES", Short: "ESTS", Suffix: true},
	{Code: "260", Full: "ESTUARY", Short: "ESTUARY", Suffix: true},
	{Code: "261", Full: "EXPRESO", Short: "EXPRESO", Spanish: true, Translation: "EXPRESSWAY ", Prefix: true},
	{Code: "262", Full: "EXPRESSWAY", Short: "EXPY", Prefix: true, Suffix: true},
	{Code: "263", Full: "EXTENSION", Short: "EXT", Prefix: true, Suffix: true},
	{Code: "264", Full: "FACILITY", Short: "FACLTY", Suffix: true},
	{Code: "265", Full: "FAIRGROUNDS", Short: "FAIRGROUNDS", Suffix: true},
	{Code: "266", Full: "FALLS", Short: "FLS", Prefix: true, Suffix: true},
	{Code: "267", Full: "FARM", Short: "FRM", Suffix: true},
	{Code: "268", Full: "FARM ROAD", Short: "FARM RD", Prefix: true},
	{Code: "269", Full: "FARM-TO-MARKET", Short: "ROAD FM", Prefix: true},
	{Code: "275", Full: "FENCE LINE", Short: "FENCE LINE", Suffix: true},
	{Code: "276", Full: "FERRY CROSSING", Short: "FERRY CROSSING", Prefix: true, Suffix: true},
	{Code: "277", Full: "FIELD", Short: "FLD", Suffix: true},
	{Code: "278", Full: "FIRE CONTROL ROAD", Short: "FIRE CNTRL RD", Prefix: true},
	{Code: "279", Full: "FIRE DEPARTMENT", Short: "FIRE DEPT", Suffix: true},
	{Code: "280", Full: "FIRE DISTRICT ROAD", Short: "FIRE DIST RD", Prefix: true},
	{Code: "281", Full: "FIRE LANE", Short: "FIRE LN", Prefix: true},
	{Code: "282", Full: "FIRE ROAD", Short: "FIRE RD", Prefix: true},
	{Code: "283", Full: "FIRE ROUTE", Short: "FIRE RTE", Prefix: true},
	{Code: "284", Full: "FIRE STATION", Short: "FIRE STA", Prefix: true, Suffix: true},
	{Code: "285", Full: "FIRE TRAIL", Short: "FIRE TRL", Prefix: true},
	{Code: "286", Full: "FLOWAGE", Short: "FLOWAGE", Suffix: true},
	{Code: "287", Full: "FLUME", Short: "FLUME", Suffix: true},
	{Code: "288", Full: "FOREST", Short: "FRST", Suffix: true},
	{Code: "289", Full: "FOREST HIGHWAY", Short: "FOREST HWY", Prefix: true, Suffix: true},
	{Code: "290", Full: "FOREST ROAD", Short: "FOREST RD", Prefix: true},
	{Code: "291", Full: "FOREST ROUTE", Short: "FOREST RTE", Prefix: true},
	{Code: "292", Full: "FOREST SERVICE ROAD", Short: "FS RD", Prefix: true},
	{Code: "293", Full: "FORK", Short: "FRK", Suffix: true},
	{Code: "294", Full: "FORT", Short: "FT", Prefix: true},
	{Code: "295", Full: "FOUR-WHEEL DRIVE TRAIL", Short: "4WD TRL", Prefix: true, Suffix: true},
	{Code: "296", Full: "FRATERNITY", Short: "FRTRNTY", Suffix: true},
	{Code: "297", Full: "FREEWAY", Short: "FWY", Suffix: true},
	{Code: "298", Full: "GARAGE", Short: "GRGE", Suffix: true},
	{Code: "299", Full: "GARDENS", Short: "GDNS", Suffix: true},
	{Code: "303", Full: "GLACIER", Short: "GLACIER", Suffix: true},
	{Code: "304", Full: "GLEN", Short: "GLN", Suffix: true},
	{Code: "305", Full: "GOLF CLUB", Short: "GOLF CLUB", Prefix: true, Suffix: true},
	{Code: "306", Full: "GOLF COURSE", Short: "GOLF COURSE", Prefix: true, Suffix: true},
	{Code: "307", Full: "GRADE", Short: "GRADE", Suffix: true},
	{Code: "309", Full: "GREEN", Short: "GRN", Suffix: true},
	{Code: "310", Full: "GROUP HOME", Short: "GROUP HOME", Suffix: true},
	{Code: "311", Full: "GULCH", Short: "GULCH", Suffix: true},
	{Code: "312", Full: "GULF", Short: "GULF", Prefix: true, Suffix: true},
	{Code: "313", Full: "GULLY", Short: "GULLY", Suffix: true},
	{Code: "314", Full: "HALFWAY HOUSE", Short: "HALFWAY HOUSE", Suffix: true},
	{Code: "315", Full: "HALL", Short: "HALL", Suffix: true},
	{Code: "316", Full: "HARBOR", Short: "HBR", Suffix: true},
	{Code: "317", Full: "HEIGHTS", Short: "HTS", Suffix: true},
	{Code: "321", Full: "HIGH SCHOOL", Short: "HIGH SCHOOL", Suffix: true},
	{Code: "322", Full: "HIGHWAY", Short: "HWY", Prefix: true, Suffix: true},
	{Code: "323", Full: "HILL", Short: "HL", Suffix: true},
	{Code: "324", Full: "HOLLOW", Short: "HOLW", Suffix: true},
	{Code: "325", Full: "HOME", Short: "HOME", Prefix: true, Suffix: true},
	{Code: "326", Full: "HOSPITAL", Short: "HOSP", Prefix: true, Suffix: true},
	{Code: "327", Full: "HOSTEL", Short: "HOSTEL", Suffix: true},
	{Code: "328", Full: "HOTEL", Short: "HOTEL", Prefix: true, Suffix: true},
	{Code: "329", Full: "HOUSE", Short: "HSE", Prefix: true, Suffix: true},
	{Code: "330", Full: "HOUSING", Short: "HSNG", Prefix: true, Suffix: true},
	{Code: "332", Full: "IGLESIA", Short: "IGLESIA", Spanish: true, Translation: "CHURCH", Prefix: true},
	{Code: "333", Full: "INDIAN ROUTE", Short: "INDIAN RTE", Prefix: true},
	{Code: "334", Full: "INDIAN SERVICE ROUTE", Short: "INDIAN SVC RTE", Prefix: true},
	{Code: "336", Full: "INDUSTRIAL PARK", Short: "INDL PARK", Suffix: true},
	{Code: "337", Full: "INLET", Short: "INLT", Suffix: true},
	{Code: "338", Full: "INN", Short: "INN", Prefix: true, Suffix: true},
	{Code: "339", Full: "INSTITUTE", Short: "INST", Prefix: true, Suffix: true},
	{Code: "340", Full: "INSTITUTION", Short: "INSTN", Suffix: true},
	{Code: "341", Full: "INSTITUTO", Short: "INSTITUTO", Spanish: true, Translation: "INSTITUTE", Prefix: true},
	{Code: "342", Full: "INTERMEDIATE SCHOOL", Short: "INTER SCHOOL", Suffix: true},
	{Code: "344", Full: "INTERSTATE HIGHWAY", Short: "I-", Prefix: true},
	{Code: "345", Full: "ISLA", Short: "ISLA", Spanish: true, Translation: "ISLAND", Prefix: true},
	{Code: "346", Full: "ISLAND", Short: "IS", Suffix: true},
	{Code: "347", Full: "ISLANDS", Short: "ISS", Prefix: true, Suffix: true},
	{Code: "348", Full: "ISLE", Short: "ISLE", Prefix: true, Suffix: true},
	{Code: "349", Full: "JAIL", Short: "JAIL", Suffix: true},
	{Code: "351", Full: "JEEP TRAIL", Short: "JEEP TRL", Prefix: true, Suffix: true},
	{Code: "352", Full: "JUNCTION", Short: "JUNCTION", Suffix: true},
	{Code: "353", Full: "JUNIOR HIGH SCHOOL", Short: "JR HS", Suffix: true},
	{Code: "356", Full: "KILL", Short: "KILL", Prefix: true, Suffix: true},
	{Code: "357", Full: "LAGO", Short: "LAGO", Spanish: true, Translation: "LAKE ", Prefix: true},
	{Code: "358", Full: "LAGOON", Short: "LAGOON", Suffix: true},
	{Code: "360", Full: "LAGUNA", Short: "LAGUNA", Spanish: true, Translation: "LAGOON ", Prefix: true},
	{Code: "361", Full: "LAKE", Short: "LK", Prefix: true, Suffix: true},
	{Code: "362", Full: "LAKES", Short: "LKS", Suffix: true},
	{Code: "363", Full: "LANDFILL", Short: "LNDFLL", Suffix: true},
	{Code: "364", Full: "LANDING", Short: "LNDG", Suffix: true},
	{Code: "365", Full: "LANDING AREA", Short: "LANDING AREA", Prefix: true, Suffix: true},
	{Code: "366", Full: "LANDING FIELD", Short: "LANDING FLD", Prefix: true, Suffix: true},
	{Code: "367", Full: "LANDING STRIP", Short: "LANDING STRP", Prefix: true, Suffix: true},
	{Code: "368", Full: "LANE", Short: "LN", Prefix: true, Suffix: true},
	{Code: "369", Full: "LATERAL", Short: "LATERAL", Prefix: true, Suffix: true},
	{Code: "370", Full: "LEVEE", Short: "LEVEE", Prefix: true, Suffix: true},
	{Code: "371", Full: "LIBRARY", Short: "LBRY", Prefix: true, Suffix: true},
	{Code: "372", Full: "LIFT", Short: "LIFT", Prefix: true, Suffix: true},
	{Code: "373", Full: "LIGHTHOUSE", Short: "LIGHTHOUSE", Suffix: true},
	{Code: "374", Full: "LINE", Short: "LINE", Prefix: true, Suffix: true},
	{Code: "376", Full: "LODGE", Short: "LDG", Suffix: true},
	{Code: "377", Full: "LOGGING ROAD", Short: "LOGGING RD", Prefix: true, Suffix: true},
	{Code: "378", Full: "LOOP", Short: "LOOP", Prefix: true, Suffix: true},
	{Code: "379", Full: "MALL", Short: "MALL", Prefix: true, Suffix: true},
	{Code: "380", Full: "MANOR", Short: "MNR", Suffix: true},
	{Code: "381", Full: "MAR", Short: "MAR", Spanish: true, Translation: "SEA ", Prefix: true},
	{Code: "382", Full: "MARGINAL", Short: "MARGINAL", Spanish: true, Translation: "SERVICE ROAD ", Prefix: true},
	{Code: "383", Full: "MARINA", Short: "MRNA", Suffix: true},
	{Code: "384", Full: "MARSH", Short: "MARSH", Suffix: true},
	{Code: "385", Full: "MEADOWS", Short: "MDWS", Suffix: true},
	{Code: "386", Full: "MEDICAL BUILDING", Short: "MEDICAL BLDG", Suffix: true},
	{Code: "387", Full: "MEDICAL CENTER", Short: "MEDICAL CTR", Prefix: true, Suffix: true},
	{Code: "388", Full: "MEMORIAL", Short: "MEML", Suffix: true},
	{Code: "389", Full: "MEMORIAL GARDENS", Short: "MEMORIAL GNDS", Suffix: true},
	{Code: "390", Full: "MEMORIAL PARK", Short: "MEMORIAL PK", Suffix: true},
	{Code: "391", Full: "MESA", Short: "MESA", Prefix: true, Suffix: true},
	{Code: "392", Full: "MIDDLE SCHOOL", Short: "MID SCHL", Suffix: true},
	{Code: "393", Full: "MILITARY RESERVATION", Short: "MIL RES", Suffix: true},
	{Code: "394", Full: "MILLPOND", Short: "MILLPOND", Suffix: true},
	{Code: "395", Full: "MINE", Short: "MINE", Suffix: true},
	{Code: "396", Full: "MISSION", Short: "MSSN", Prefix: true, Suffix: true},
	{Code: "397", Full: "MOBILE HOME COMMUNITY", Short: "MOBILE HM CMTY", Prefix: true, Suffix: true},
	{Code: "398", Full: "MOBILE HOME ESTATES", Short: "MOBILE HM EST", Prefix: true, Suffix: true},
	{Code: "399", Full: "MOBILE HOME PARK", Short: "MOBILE HM PK", Prefix: true, Suffix: true},
	{Code: "400", Full: "MONASTERY", Short: "MONSTRY", Prefix: true, Suffix: true},
	{Code: "401", Full: "MONUMENT", Short: "MNMT", Suffix: true},
	{Code: "403", Full: "MOSQUE", Short: "MOSQUE", Prefix: true, Suffix: true},
	{Code: "404", Full: "MOTEL", Short: "MTL", Prefix: true, Suffix: true},
	{Code: "405", Full: "MOTOR LODGE", Short: "MOTOR LODGE", Suffix: true},
	{Code: "406", Full: "MOTORWAY", Short: "MTWY", Suffix: true},
	{Code: "407", Full: "MOUNT", Short: "MT", Prefix: true, Suffix: true},
	{Code: "408", Full: "MOUNTAIN", Short: "MTN", Suffix: true},
	{Code: "411", Full: "MUSEUM", Short: "MUS", Prefix: true, Suffix: true},
	{Code: "412", Full: "NATIONAL BATTLEFIELD", Short: "NATL BFLD", Suffix: true},
	{Code: "413", Full: "NATIONAL BATTLEFIELD PARK", Short: "NATL BFLD PK", Suffix: true},
	{Code: "414", Full: "NATIONAL BATTLEFIELD SITE", Short: "NATL BFLD SITE", Suffix: true},
	{Code: "415", Full: "NATIONAL CONSERVATION AREA", Short: "NATL CNSV AREA", Suffix: true},
	{Code: "416", Full: "NATIONAL FOREST", Short: "NATL FOREST", Suffix: true},
	{Code: "417", Full: "NATIONAL FOREST DEVELOPMENT ROAD", Short: "NAT FOR DEV RD", Prefix: true},
	{Code: "419", Full: "NATIONAL GRASSLANDS", Short: "NATL GRSSLNDS", Suffix: true},
	{Code: "420", Full: "NATIONAL HISTORIC SITE", Short: "NATL HIST SITE", Suffix: true},
	{Code: "421", Full: "NATIONAL HISTORICAL PARK", Short: "NATL HIST PK", Suffix: true},
	{Code: "422", Full: "NATIONAL LAKESHORE", Short: "NATL LKSHR", Suffix: true},
	{Code: "423", Full: "NATIONAL MEMORIAL", Short: "NATL MEML", Suffix: true},
	{Code: "424", Full: "NATIONAL MILITARY PARK", Short: "NATL MIL PK", Suffix: true},
	{Code: "425", Full: "NATIONAL MONUMENT", Short: "NATL MNMT", Suffix: true},
	{Code: "426", Full: "NATIONAL PARK", Short: "NATL PK", Suffix: true},
	{Code: "427", Full: "NATIONAL PRESERVE", Short: "NATL PRSV", Suffix: true},
	{Code: "428", Full: "NATIONAL RECREATION AREA", Short: "NATL REC AREA", Suffix: true},
	{Code: "429", Full: "NATIONAL RECREATIONAL RIVER", Short: "NATL REC RIV", Suffix: true},
	{Code: "430", Full: "NATIONAL RESERVE", Short: "NATL RESV", Suffix: true},
	{Code: "431", Full: "NATIONAL RIVER", Short: "NATL RIV", Suffix: true},
	{Code: "432", Full: "NATIONAL SCENIC AREA", Short: "NATL SC AREA", Suffix: true},
	{Code: "433", Full: "NATIONAL SCENIC RIVER", Short: "NATL SC RIV", Suffix: true},
	{Code: "435", Full: "NATIONAL SCENIC RIVERWAYS", Short: "NATL SC RVRWYS", Suffix: true},
	{Code: "436", Full: "NATIONAL SCENIC TRAIL", Short: "NATL SC TRL", Suffix: true},
	{Code: "437", Full: "NATIONAL SEASHORE", Short: "NATL SHR", Suffix: true},
	{Code: "438", Full: "NATIONAL WILDLIFE REFUGE", Short: "NATL WLD RFG", Suffix: true},
	{Code: "439", Full: "NAVAJO SERVICE ROUTE", Short: "NAVAJO SVC RTE", Prefix: true},
	{Code: "440", Full: "NAVAL AIR STATION", Short: "NAVAL AIR STA", Suffix: true},
	{Code: "442", Full: "NURSING HOME", Short: "NURSE HOME", Suffix: true},
	{Code: "444", Full: "OCEAN", Short: "OCEAN", Suffix: true},
	{Code: "445", Full: "OCEANO", Short: "OCÉANO", Spanish: true, Translation: "OCEAN ", Prefix: true},
	{Code: "446", Full: "OFFICE", Short: "OFC", Prefix: true, Suffix: true},
	{Code: "447", Full: "OFFICE BUILDING", Short: "OFFICE BLDG", Suffix: true},
	{Code: "449", Full: "OFFICE PARK", Short: "OFFICE PARK", Suffix: true},
	{Code: "698", Full: "ORCHARD", Short: "ORCHARD", Suffix: true},
	{Code: "451", Full: "ORCHARDS", Short: "ORCHRDS", Suffix: true},
	{Code: "452", Full: "ORPHANAGE", Short: "ORPHANAGE", Suffix: true},
	{Code: "453", Full: "OUTLET", Short: "OUTLET", Suffix: true},
	{Code: "454", Full: "OVAL", Short: "OVAL", Suffix: true},
	{Code: "455", Full: "OVERPASS", Short: "OPAS", Suffix: true},
	{Code: "456", Full: "PARISH ROAD", Short: "PARISH RD", Prefix: true},
	{Code: "457", Full: "PARK", Short: "PARK", Suffix: true},
	{Code: "458", Full: "PARK AND RIDE", Short: "PARK AND RIDE", Suffix: true},
	{Code: "460", Full: "PARKWAY", Short: "PKWY", Suffix: true},
	{Code: "706", Full: "PARQ", Short: "PARQ", Spanish: true, Translation: "PARK ", Prefix: true},
	{Code: "461", Full: "PARQUE", Short: "PARQUE", Spanish: true, Translation: "PARK ", Prefix: true},
	{Code: "462", Full: "PASAJE", Short: "PASAJE", Spanish: true, Translation: "PASSAGE ", Prefix: true},
	{Code: "463", Full: "PASEO", Short: "PSO", Spanish: true, Translation: "PATH ", Prefix: true},
	{Code: "464", Full: "PASS", Short: "PASS", Prefix: true, Suffix: true},
	{Code: "465", Full: "PASSAGE", Short: "PSGE", Prefix: true, Suffix: true},
	{Code: "466", Full: "PATH", Short: "PATH", Suffix: true},
	{Code: "682", Full: "PAVILION", Short: "PAVILION", Suffix: true},
	{Code: "467", Full: "PEAK", Short: "PEAK", Suffix: true},
	{Code: "705", Full: "PENITENTIARY", Short: "PENITENTIARY", Suffix: true},
	{Code: "468", Full: "PIER", Short: "PIER", Prefix: true, Suffix: true},
	{Code: "469", Full: "PIKE", Short: "PIKE", Suffix: true},
	{Code: "470", Full: "PIPELINE", Short: "PIPELINE", Suffix: true},
	{Code: "472", Full: "PLACE", Short: "PL", Suffix: true},
	{Code: "473", Full: "PLACITA", Short: "PLA", Spanish: true, Translation: "LITTLE PLAZA ", Prefix: true},
	{Code: "474", Full: "PLANT", Short: "PLNT", Suffix: true},
	{Code: "683", Full: "PLANTATION", Short: "PLANTATION", Suffix: true},
	{Code: "475", Full: "PLAYA", Short: "PLAYA", Spanish: true, Translation: "BEACH ", Prefix: true},
	{Code: "476", Full: "PLAYGROUND", Short: "PLAYGROUND", Suffix: true},
	{Code: "477", Full: "PLAZA", Short: "PLZ", Prefix: true, Suffix: true},
	{Code: "478", Full: "POINT", Short: "PT", Prefix: true, Suffix: true},
	{Code: "479", Full: "POINTE", Short: "POINTE", Suffix: true},
	{Code: "480", Full: "POLICE DEPARTMENT", Short: "POLICE DEPT", Prefix: true, Suffix: true},
	{Code: "481", Full: "POLICE STATION", Short: "POLICE STATION", Prefix: true, Suffix: true},
	{Code: "482", Full: "POND", Short: "POND", Prefix: true, Suffix: true},
	{Code: "483", Full: "PONDS", Short: "PONDS", Suffix: true},
	{Code: "485", Full: "PORT", Short: "PRT", Prefix: true, Suffix: true},
	{Code: "486", Full: "POST OFFICE", Short: "POST OFFICE", Suffix: true},
	{Code: "487", Full: "POWER LINE", Short: "POWER LINE", Suffix: true},
	{Code: "691", Full: "POWER PLANT", Short: "POWER PLANT", Suffix: true},
	{Code: "488", Full: "PRAIRIE", Short: "PR", Suffix: true},
	{Code: "489", Full: "PRESERVE", Short: "PRESERVE", Suffix: true},
	{Code: "491", Full: "PRISON", Short: "PRISON", Suffix: true},
	{Code: "690", Full: "PRISON FARM", Short: "PRISON FARM", Suffix: true},
	{Code: "685", Full: "PROMENADE", Short: "PROMENADE", Suffix: true},
	{Code: "492", Full: "PRONG", Short: "PRONG", Suffix: true},
	{Code: "494", Full: "PUENTE", Short: "PUENTE", Spanish: true, Translation: "BRIDGE ", Prefix: true},
	{Code: "495", Full: "QUADRANGLE", Short: "QUADRANGLE", Suffix: true},
	{Code: "496", Full: "QUARRY", Short: "QUAR", Suffix: true},
	{Code: "686", Full: "QUARTERS", Short: "QUARTERS", Suffix: true},
	{Code: "497", Full: "QUEBRADA", Short: "QBDA", Spanish: true, Translation: "CREEK ", Prefix: true},
	{Code: "499", Full: "RACE", Short: "RACE", Suffix: true},
	{Code: "501", Full: "RAIL", Short: "RAIL", Suffix: true},
	{Code: "502", Full: "RAIL LINK", Short: "RAIL LINK", Prefix: true, Suffix: true},
	{Code: "504", Full: "RAILNET", Short: "RAILNET", Suffix: true},
	{Code: "505", Full: "RAILROAD", Short: "RR", Suffix: true},
	{Code: "506", Full: "RAILWAY", Short: "RLWY", Suffix: true},
	{Code: "507", Full: "RAMAL", Short: "RAMAL", Spanish: true, Translation: "SHORT STREET ", Prefix: true},
	{Code: "508", Full: "RAMP", Short: "RAMP", Suffix: true},
	{Code: "510", Full: "RANCH ROAD", Short: "RANCH RD", Prefix: true},
	{Code: "511", Full: "RANCH TO MARKET ROAD", Short: "RM", Prefix: true},
	{Code: "512", Full: "RANCHO", Short: "RCH", Spanish: true, Translation: "RANCH OR FARM ", Prefix: true},
	{Code: "513", Full: "RAVINE", Short: "RAVINE", Suffix: true},
	{Code: "514", Full: "RECREATION AREA", Short: "REC AREA", Suffix: true},
	{Code: "515", Full: "REFORMATORY", Short: "REFORMATORY", Suffix: true},
	{Code: "516", Full: "REFUGE", Short: "REFUGE", Suffix: true},
	{Code: "518", Full: "REGIONAL PARK", Short: "REGIONAL PK", Suffix: true},
	{Code: "519", Full: "RESERVATION", Short: "RESERVATION", Suffix: true},
	{Code: "520", Full: "RESERVATION HIGHWAY", Short: "RESVN HWY", Prefix: true},
	{Code: "521", Full: "RESERVE", Short: "RESV", Suffix: true},
	{Code: "522", Full: "RESERVOIR", Short: "RESERVOIR", Prefix: true, Suffix: true},
	{Code: "524", Full: "RESIDENCE HALL", Short: "RES HALL", Suffix: true},
	{Code: "525", Full: "RESIDENCIAL", Short: "RESIDENCIAL", Spanish: true, Translation: "PUBLIC HOUSING PROJECT ", Prefix: true},
	{Code: "526", Full: "RESORT", Short: "RESRT", Suffix: true},
	{Code: "688", Full: "REST HOME", Short: "REST HOME", Suffix: true},
	{Code: "527", Full: "RETIREMENT HOME", Short: "RETIREMENT HME", Suffix: true},
	{Code: "528", Full: "RETIREMENT VILLAGE", Short: "RETIREMENT VLG", Suffix: true},
	{Code: "529", Full: "RIDGE", Short: "RDG", Suffix: true},
	{Code: "543", Full: "RIO", Short: "RÍO", Spanish: true, Translation: "RIVER ", Prefix: true},
	{Code: "530", Full: "RIVER", Short: "RIV", Suffix: true},
	{Code: "531", Full: "ROAD", Short: "RD", Prefix: true, Suffix: true},
	{Code: "533", Full: "ROADWAY", Short: "ROADWAY", Suffix: true},
	{Code: "535", Full: "ROCK", Short: "ROCK", Prefix: true, Suffix: true},
	{Code: "536", Full: "ROOMING HOUSE", Short: "ROOMING HSE", Suffix: true},
	{Code: "537", Full: "ROUTE", Short: "RTE", Prefix: true, Suffix: true},
	{Code: "538", Full: "ROW", Short: "ROW", Prefix: true, Suffix: true},
	{Code: "539", Full: "RUE", Short: "RUE", Prefix: true, Suffix: true},
	{Code: "540", Full: "RUN", Short: "RUN", Suffix: true},
	{Code: "541", Full: "RUNWAY", Short: "RUNWAY", Prefix: true, Suffix: true},
	{Code: "542", Full: "RUTA", Short: "RUTA", Spanish: true, Translation: "ROUTE ", Prefix: true},
	{Code: "498", Full: "RV PARK", Short: "RV PARK", Suffix: true},
	{Code: "545", Full: "SANITARIUM", Short: "SANITARIUM", Suffix: true},
	{Code: "546", Full: "SCHOOL", Short: "SCHL", Prefix: true, Suffix: true},
	{Code: "549", Full: "SEA", Short: "SEA", Prefix: true, Suffix: true},
	{Code: "550", Full: "SEASHORE", Short: "SEASHORE", Suffix: true},
	{Code: "552", Full: "SECTOR", Short: "SEC", Spanish: true, Translation: "SECTOR ", Prefix: true},
	{Code: "553", Full: "SEMINARY", Short: "SMRY", Prefix: true, Suffix: true},
	{Code: "554", Full: "SENDERO", Short: "SENDERO", Spanish: true, Translation: "FOOT PATH ", Prefix: true},
	{Code: "555", Full: "SERVICE ROAD", Short: "SVC RD", Prefix: true, Suffix: true},
	{Code: "556", Full: "SHELTER", Short: "SHELTER", Suffix: true},
	{Code: "558", Full: "SHOP", Short: "SHOP", Suffix: true},
	{Code: "699", Full: "SHOPPING CENTER", Short: "SHOPPING CTR", Suffix: true},
	{Code: "560", Full: "SHOPPING MALL", Short: "SHOPPING MALL", Suffix: true},
	{Code: "700", Full: "SHOPPING PLAZA", Short: "SHOPPING PLZ", Suffix: true},
	{Code: "703", Full: "SITE", Short: "SITE", Suffix: true},
	{Code: "564", Full: "SKYWAY", Short: "SKWY", Prefix: true, Suffix: true},
	{Code: "565", Full: "SLOUGH", Short: "SLOUGH", Suffix: true},
	{Code: "566", Full: "SONDA", Short: "SONDA", Spanish: true, Translation: "SOUND ", Prefix: true},
	{Code: "567", Full: "SORORITY", Short: "SORORITY", Prefix: true, Suffix: true},
	{Code: "568", Full: "SOUND", Short: "SND", Prefix: true},
	{Code: "569", Full: "SPA", Short: "SPA", Prefix: true, Suffix: true},
	{Code: "570", Full: "SPEEDWAY", Short: "SPEEDWAY", Prefix: true, Suffix: true},
	{Code: "571", Full: "SPRING", Short: "SPG", Suffix: true},
	{Code: "572", Full: "SPUR", Short: "SPUR", Prefix: true, Suffix: true},
	{Code: "573", Full: "SQUARE", Short: "SQ", Prefix: true, Suffix: true},
	{Code: "575", Full: "STATE BEACH", Short: "STATE BEACH", Suffix: true},
	{Code: "577", Full: "STATE FOREST", Short: "STATE FOREST", Suffix: true},
	{Code: "578", Full: "STATE FOREST SERVICE ROAD", Short: "ST FS RD", Prefix: true},
	{Code: "579", Full: "STATE HIGHWAY", Short: "STATE HWY", Prefix: true},
	{Code: "580", Full: "STATE HOSPITAL", Short: "STATE HOSPITAL", Prefix: true, Suffix: true},
	{Code: "581", Full: "STATE LOOP", Short: "STATE LOOP", Prefix: true},
	{Code: "582", Full: "STATE PARK", Short: "STATE PARK", Suffix: true},
	{Code: "584", Full: "STATE PRISON", Short: "STATE PRISON", Suffix: true},
	{Code: "585", Full: "STATE ROAD", Short: "STATE RD", Prefix: true},
	{Code: "586", Full: "STATE ROUTE", Short: "STATE RTE", Prefix: true},
	{Code: "588", Full: "STATE SPUR", Short: "STATE SPUR", Prefix: true},
	{Code: "589", Full: "STATE TRUNK HIGHWAY", Short: "ST TRUNK HWY", Prefix: true},
	{Code: "591", Full: "STATION", Short: "STA", Suffix: true},
	{Code: "592", Full: "STRAIT", Short: "STRAIT", Prefix: true, Suffix: true},
	{Code: "593", Full: "STRAVENUE", Short: "STRA", Suffix: true},
	{Code: "594", Full: "STREAM", Short: "STRM", Suffix: true},
	{Code: "595", Full: "STREET", Short: "ST", Suffix: true},
	{Code: "596", Full: "STRIP", Short: "STRIP", Prefix: true, Suffix: true},
	{Code: "599", Full: "SWAMP", Short: "SWAMP", Suffix: true},
	{Code: "600", Full: "SYNAGOGUE", Short: "SYNAGOGUE", Prefix: true, Suffix: true},
	{Code: "601", Full: "TANK", Short: "TANK", Suffix: true},
	{Code: "603", Full: "TEMPLE", Short: "TMPL", Prefix: true, Suffix: true},
	{Code: "604", Full: "TERMINAL", Short: "TRMNL", Suffix: true},
	{Code: "605", Full: "TERRACE", Short: "TER", Prefix: true, Suffix: true},
	{Code: "687", Full: "THOROUGHFARE", Short: "THOROUGHFARE", Suffix: true},
	{Code: "607", Full: "TOLL BOOTH", Short: "TOLL BOOTH", Prefix: true, Suffix: true},
	{Code: "701", Full: "TOLL ROAD", Short: "TOLL RD", Suffix: true},
	{Code: "610", Full: "TOLLWAY", Short: "TOLLWAY", Suffix: true},
	{Code: "611", Full: "TOWER", Short: "TWR", Prefix: true, Suffix: true},
	{Code: "612", Full: "TOWN CENTER", Short: "TOWN CTR", Prefix: true, Suffix: true},
	{Code: "613", Full: "TOWN HALL", Short: "TOWN HALL", Suffix: true},
	{Code: "614", Full: "TOWN HIGHWAY", Short: "TOWN HWY", Prefix: true},
	{Code: "615", Full: "TOWN ROAD", Short: "TOWN RD", Prefix: true},
	{Code: "616", Full: "TOWNE CENTER", Short: "TOWNE CTR", Prefix: true, Suffix: true},
	{Code: "617", Full: "TOWNSHIP HIGHWAY", Short: "TWP HWY", Prefix: true},
	{Code: "618", Full: "TOWNSHIP ROAD", Short: "TWP RD", Prefix: true},
	{Code: "619", Full: "TRACE", Short: "TRCE", Suffix: true},
	{Code: "620", Full: "TRACK", Short: "TRAK", Prefix: true, Suffix: true},
	{Code: "621", Full: "TRAFFICWAY", Short: "TRFY", Suffix: true},
	{Code: "622", Full: "TRAIL", Short: "TRL", Prefix: true, Suffix: true},
	{Code: "623", Full: "TRAILER COURT", Short: "TRAILER CT", Suffix: true},
	{Code: "624", Full: "TRAILER PARK", Short: "TRAILER PK", Suffix: true},
	{Code: "628", Full: "TRANSMISSION LINE", Short: "TRANS LN", Suffix: true},
	{Code: "702", Full: "TREATMENT PLANT", Short: "TRMT PLANT", Prefix: true, Suffix: true},
	{Code: "630", Full: "TRIBAL ROAD", Short: "TRIBAL RD", Prefix: true},
	{Code: "632", Full: "TROLLEY", Short: "TROLLEY", Prefix: true, Suffix: true},
	{Code: "633", Full: "TRUCK TRAIL", Short: "TRUCK TRL", Prefix: true, Suffix: true},
	{Code: "636", Full: "TÚNEL", Short: "TÚNEL", Spanish: true, Translation: "TUNNEL ", Prefix: true},
	{Code: "634", Full: "TUNNEL", Short: "TUNL", Prefix: true, Suffix: true},
	{Code: "635", Full: "TURNPIKE", Short: "TPKE", Suffix: true},
	{Code: "637", Full: "UNDERPASS", Short: "UPAS", Prefix: true, Suffix: true},
	{Code: "642", Full: "UNIVERSIDAD", Short: "UNIVERSIDAD", Spanish: true, Translation: "UNIVERSITY OR COLLEGE ", Prefix: true},
	{Code: "643", Full: "UNIVERSITY", Short: "UNIV", Prefix: true, Suffix: true},
	{Code: "638", Full: "US FOREST SERVICE HIGHWAY", Short: "USFS HWY", Prefix: true},
	{Code: "639", Full: "US FOREST SERVICE ROAD", Short: "USFS RD", Prefix: true},
	{Code: "640", Full: "US HIGHWAY", Short: "US HWY", Prefix: true},
	{Code: "641", Full: "US ROUTE", Short: "US RTE", Prefix: true},
	{Code: "644", Full: "VALLEY", Short: "VLY", Suffix: true},
	{Code: "645", Full: "VEREDA", Short: "VER", Spanish: true, Translation: "PATH ", Prefix: true},
	{Code: "655", Full: "VIA", Short: "VIA", Spanish: true, Translation: "WAY ", Prefix: true},
	{Code: "646", Full: "VIADUCT", Short: "VIADUCT", Suffix: true},
	{Code: "647", Full: "VIEW", Short: "VW", Suffix: true},
	{Code: "648", Full: "VILLA", Short: "VILLA", Prefix: true, Suffix: true},
	{Code: "649", Full: "VILLAGE", Short: "VLG", Prefix: true, Suffix: true},
	{Code: "650", Full: "VILLAGE CENTER", Short: "VILLAGE CTR", Prefix: true, Suffix: true},
	{Code: "697", Full: "VINEYARD", Short: "VINEYARD", Suffix: true},
	{Code: "652", Full: "VINEYARDS", Short: "VINEYARDS", Suffix: true},
	{Code: "654", Full: "VISTA", Short: "VIS", Spanish: true, Translation: "VIEW", Prefix: true, Suffix: true},
	{Code: "656", Full: "WALK", Short: "WALK", Suffix: true},
	{Code: "657", Full: "WALKWAY", Short: "WALKWAY", Suffix: true},
	{Code: "659", Full: "WASH", Short: "WASH", Suffix: true},
	{Code: "660", Full: "WATERWAY", Short: "WATERWAY", Suffix: true},
	{Code: "661", Full: "WAY", Short: "WAY", Suffix: true},
	{Code: "663", Full: "WHARF", Short: "WHARF", Suffix: true},
	{Code: "665", Full: "WILD AND SCENIC RIVER", Short: "WLD N SNC RIV", Suffix: true},
	{Code: "664", Full: "WILD RIVER", Short: "WILD RIVER", Suffix: true},
	{Code: "666", Full: "WILDERNESS", Short: "WILDERNESS", Suffix: true},
	{Code: "667", Full: "WILDERNESS PARK", Short: "WILDERENSS PK", Suffix: true},
	{Code: "668", Full: "WILDLIFE MANAGEMENT AREA", Short: "WLDLF MGT AREA", Suffix: true},
	{Code: "669", Full: "WINERY", Short: "WINERY", Prefix: true, Suffix: true},
	{Code: "672", Full: "YARD", Short: "YARD", Suffix: true},
	{Code: "673", Full: "YARDS", Short: "YARDS", Prefix: true, Suffix: true},
	{Code: "670", Full: "YMCA", Short: "YMCA", Prefix: true, Suffix: true},
	{Code: "671", Full: "YWCA", Short: "YWCA", Prefix: true, Suffix: true},
	{Code: "675", Full: "ZANJA", Short: "ZANJA", Spanish: true, Translation: "DITCH ", Prefix: true},
	{Code: "676", Full: "ZOO", Short: "ZOO", Prefix: true, Suffix: true}}

// All yields every feature type, in the order the appendix prints them.
func All() iter.Seq[FeatureType] {
	return slices.Values(featureTypes)
}

// Len reports how many rows All will yield.
func Len() int {
	return len(featureTypes)
}
